#!/bin/sh
#MISE description="go mod tidy"

set -e

go mod tidy

if ! git diff --exit-code -- go.mod go.sum >/dev/null 2>&1; then
  echo "go module files modified, please commit result of 'go mod tidy'!"
  git diff -- go.mod go.sum
  exit 1
fi
